### PR TITLE
Numerous fixes and updates for RS2020 and Mac builds

### PR DESCRIPTION
**Pull request by smokhov**

### CODE REVIEW

**Comment by jcelerier** [comment]
Hi, I'm afraid we've stopped maintaining this library (I haven't had any realsense camera nor Max/MSP license accessible to me for years so I can't really test / upgrade things).
Since you seem to do a lot of good work on it would you agree to have this repo to point back to yours ? e.g. I'll add a link to the readme and archive the repo.

**Comment by smokhov** [comment]
@jcelerier -- no worries, I think @robtherich is now the presumed maintainer so I've submitted the PR to his fork. Thank you for getting back on this!

**Comment by robtherich** [comment]
@jcelerier feel free to have your repo direct to https://github.com/robtherich/jit.realsense

**Comment by jcelerier** [comment]
yep doing that, thanks folks !

**Pull request closed without merging**
